In [73]:
1 + 1

21:50

# assign and display variable
a <- 1 + 1
a

[1] 2

[1] 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45
[26] 46 47 48 49 50

[1] 2

In [74]:
# displays var type
b <- 17
b
class(b)

c <- 17L
c
class(c)

d <- "This is text!"
d
class(d)

[1] 17

[1] "numeric"

[1] 17

[1] "integer"

[1] "This is text!"

[1] "character"

In [75]:
# Vector basics
# c() is for creating vectors ("concatenate")
a <- c(1, 2, 3, 4, 5)
a

# seq() is also useful
s <- seq(1, 10, 2)
s
length(s)

[1] 1 2 3 4 5

[1] 1 3 5 7 9

[1] 5

In [76]:
# Vector subsets
a[2]
a[c(2, 4)]
s[-1]   # excludes element 1
s[-(2:4)]   # exclues 2-4

# logical subsetting
d <- c(TRUE, FALSE, FALSE, TRUE, FALSE)
a[d]
s[d]

# Correspondence
a <= s
s <= a

[1] 2

[1] 2 4

[1] 3 5 7 9

[1] 1 9

[1] 1 4

[1] 1 7

[1] TRUE TRUE TRUE TRUE TRUE

[1]  TRUE FALSE FALSE FALSE FALSE

In [77]:
# Truncation
x <- c(1, 10, 8, 2, 6)
x > 4
x[x > 4]

[1] FALSE  TRUE  TRUE FALSE  TRUE

[1] 10  8  6

In [78]:
# Categorical variables are stored in factors

x <- c("M", "F", "F", "0", "M", "M")
x

x.factor <- factor(x)
x.factor

levels(x.factor)
as.numeric(x.factor)

[1] "M" "F" "F" "0" "M" "M"

[1] M F F 0 M M
Levels: 0 F M

[1] "0" "F" "M"

[1] 3 2 2 1 3 3

In [87]:
# Matrices
A <- matrix(1:8, ncol = 2)
A

B <- matrix(9:16, nrow = 4, byrow = TRUE)
B

C <- matrix(c(2, 1, 1, 4), ncol = 2)
C

D <- matrix(LETTERS[1:6], nrow = 3)
D

[,1] [,2]
[1,] 1    5   
[2,] 2    6   
[3,] 3    7   
[4,] 4    8

[,1] [,2]
[1,]  9   10  
[2,] 11   12  
[3,] 13   14  
[4,] 15   16

[,1] [,2]
[1,] 2    1   
[2,] 1    4

[,1] [,2]
[1,] A    D   
[2,] B    E   
[3,] C    F

In [90]:
A + B
A * B 
A == B 

# This performs matrix multiplication instead of elem * elem
A %*% C 

[,1] [,2]
[1,] 10   15  
[2,] 13   18  
[3,] 16   21  
[4,] 19   24

[,1] [,2]
[1,]  9    50 
[2,] 22    72 
[3,] 39    98 
[4,] 60   128

[,1]  [,2] 
[1,] FALSE FALSE
[2,] FALSE FALSE
[3,] FALSE FALSE
[4,] FALSE FALSE

[,1] [,2]
[1,]  7   21  
[2,] 10   26  
[3,] 13   31  
[4,] 16   36

In [91]:
# t() used for transposition and # solve() used for inversion

t(A)
solve(C)


[,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 5    6    7    8

[,1]       [,2]      
[1,]  0.5714286 -0.1428571
[2,] -0.1428571  0.2857143

In [92]:
# Matrix form of linear regression: 
# B = (X^T * X)^-1 * X^T * Y

Y <- c(14, 11, 14, 18, 12, 9)
Y

X0 <- rep(1, 6)     # ordered from 1 - 6
X1 <- c(2, 3, 0, 8, 4, 1)
X2 <- c(4, 2, 6, 4, 3, 2)

# produce the design matrix
X <- matrix(c(X0, X1, X2), nrow = 6)
X

[1] 14 11 14 18 12  9

[,1] [,2] [,3]
[1,] 1    2    4   
[2,] 1    3    2   
[3,] 1    0    6   
[4,] 1    8    4   
[5,] 1    4    3   
[6,] 1    1    2

In [93]:
# Least squares regression: 

B = solve(t(X) %*% X) %*% t(X) %*% Y
B

[,1]     
[1,] 5.2505543
[2,] 0.8137472
[3,] 1.5166297

In [95]:
# In proper R syntax though, we would rather use: 

m <- lm(Y ~ X1 + X2)
B <- coef(m)
B

(Intercept)          X1          X2 
  5.2505543   0.8137472   1.5166297

(Intercept)          X1          X2 
  5.2505543   0.8137472   1.5166297